### ISSUE TITLE
Fatal error: Class 'Fuwanovel\Vndb\SimpleClient' not found

### ISSUE THREAD

**Issue by wraithseeker** [Fuwanovel/VNDB-Client#1]
I cloned the project to my desktop and have installed composer and ran the following function.

composer require fuwanovel/vndb-client:~1.0@dev 

However I am getting the following error when running the basic usage php script.

Class 'Fuwanovel\Vndb\SimpleClient' not found in /Users/wraithseeker/Desktop/VNDB-Client/script.php on line 4.

**Comment by timoschaefer** [comment]
Have you ran "composer install -o" before trying to run your script?

Also, have you required an autoloader, like composer's?

```php
require __DIR__ . '/vendor/autoload.php';
```

Should be the first line in your script.

**Comment by wraithseeker** [comment]
Here are the steps that I did to install the project. I have PHP 5.6.14 installed with Composer and my setup is a Mac.

1) I cloned it to my desktop.
2) I ran `composer require fuwanovel/vndb-client:~1.0@dev` in the terminal at the VNDB-Client directory
3) I created a new script.php that consisted of the basic usage script and enclosed them with` <?php  basic usage script here ?>`

4) I added `require __DIR__ . '/vendor/autoload.php';` inside the php tag.

5) In terminal, I run php script.php and I get 

Could not open input file: script.php

**Comment by wraithseeker** [comment]
I would appreciate some hand-holding to get the basic usage right as I have not touched PHP before (I am a mobile developer).

It's throwing errors saying that I have not set my username and password.

 I tried setting it on my script and it throws errors at me.

`$client = Client::make('myname', 'mypassword');`

`PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Command [login] requires the following keys to be present: (client, clientver, password, protocol, username).' in /Users/wraithseeker/Desktop/VNDB-Client/src/Command/LoginCommand.php:70`

**Comment by timoschaefer** [comment]
I'll do my best to help you out - I've tried to get it working using the steps in the README, and there are indeed some problems with it - my bad entirely.

You'll want to run a few more things (the long version, just to make sure):

* Use an empty directory
* Fetch composer ```php -r "readfile('https://getcomposer.org/installer');" | php```
* Wait until the download finishes, then run the following commands:
* ```composer require fuwanovel/cache:~1.0@dev```
* ```composer require fuwanovel/vndb-client:~1.0@dev -o```
* Now you should be good to go, here's the script I've tried (just fetching VNDB stats):

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$client = Fuwanovel\Vndb\SimpleClient::make('leiven', 'p3n1sk0pf1234');

$response = $client->getDbStats();

var_dump($response->getData());
```

**Comment by wraithseeker** [comment]
I managed to get the vn data to be displayed and the example you showed me to be displayed properly as well. I can get most of the rest working by myself.

However there's a few minor issues that I wanted to ask.

1) I noticed that whenever I make use of the API, I get locked out pretty easily which was mentioned in the VNDB API. What's the most efficient way for me to go through the whole VN listing and retrieve data without getting locked out?

2) When I get character details, the php script throws a warning at Character.php, how do I silence that?

 `Warning: DateTimeImmutable::createFromFormat(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /Users/wraithseeker/Desktop/VNDB-Client/src/Entity/Character.php on line 179`

**Comment by timoschaefer** [comment]
1) Care to show me what you're trying to do exactly? I keep developing the client almost daily and so far haven't been limited even once.

2) PHP-specific configuration quirk. You need to set your PHP CLI's ```php.ini``` (```find / -name php.ini```) ```date.timezone``` to something, otherwise it keeps warning you, even though it falls back to ```UTC``` anyways.

So, uncomment the line and make it say ```date.timezone = 'UTC'```.

**Comment by wraithseeker** [comment]
I'm thinking of looping through the whole list in the mySQL DB in VNDB but there are limits imposed so I believe I would need the loop to "sleep" for abit so it doesn't trigger the throttle.

I just tested running the script and sometimes it gets rejected by the API with `Socket connection error`. 

My first attempt showed the error after running the script the second time.
The second attempt lasted about 5 runs of the script.

**Comment by timoschaefer** [comment]
The client isn't really made for that kind of stuff, and I don't see any reason why anyone would need to fetch everything - while possible, it just plain shouldn't be done.

I've included helpers for fetching the entirety of an **user's** VN / wish / vote list, but that's as far as I'll go.

**Comment by timoschaefer** [comment]
Your best bet is probably trying to only fetch basic information first (to save on DB time) and wait after getting locked out, then start again once you're allowed to fetch information again. Keep doing until you have all IDs, then fetch the rest in incremental steps.

I still wouldn't recommend doing this, and I think Yorhel wouldn't like you doing it either - therefore I also won't provide an easy way to do it in my client either.

Still, thank you for using it and getting me motivated enough to push for version 1.0 - further improvements coming soon. Also feel free to submit any further issues that might arise from other use cases. :)
